Entity and Goal Mappings [Draft] (Opinions Needed)
OrnitheMC/feather-mappings pull request #107
Opened 2022-11-30 18:06 UTC by MaheEvil

Opinions needed for name of newly mapped class `MobEntityActiveTargetGoal` (`C_16xvdchlc`)
- The class is essentially a variation of ActiveTargetGoal but for Non Path Finding mob entities (only used for slime in 1.8 afaik)

2022-11-30 19:35 UTC, SpaceWalkerRS commented
Then there is also `C_94dijdhgf` which seems to be a variation that takes scoreboard teams into account. Both of these variations seem to me to be more basic versions, with the only real difference being that there's fewer calculations in the target filters?

2022-11-30 20:21 UTC, InspectorBoat commented
`SimpleActiveTargetGoal`?

2022-12-01 01:38 UTC, MaheEvil commented
> Then there is also `C_94dijdhgf` which seems to be a variation that takes scoreboard teams into account. Both of these variations seem to me to be more basic versions, with the only real difference being that there's fewer calculations in the target filters?

I currently have that named as `MobEntityPlayerTargetGoal` temporarily, as it's filter is hardcoded to only accept PlayerEntities  
![image](https://user-images.githubusercontent.com/66691814/204944997-b20f9191-4cd3-4403-b5c9-ede78d618d98.png)

2022-12-02 17:03 UTC, SpaceWalkerRS commented
Perhaps the following could work: `C_64qcggszu` -> `NearestAttackableTargetGoal`, `C_16xvdchlc` -> `NearestTargetGoal`, `C_94dijdhgf` -> `NearestAttackablePlayerGoal`.

Also a few other comments:
- Generally, use `pos` not `blockPos`, `state` not `blockState`, `stack` not `itemStack`, `client` not `mcClient`.
- Generally, don't put the type of a field/method in its name: `getFishLoot` not `getFishLootList`, `target` not `targetEntity`, `mob` not `mobEntity`, etc. There are exceptions but most of the time these type descriptors are redundant and could (or should) be replaced by a descriptor of what the field/method is used for (e.g. `followTarget` or `attackTarget` rather than `targetEntity`).

2022-12-02 17:18 UTC, MaheEvil commented
> Perhaps the following could work: `C_64qcggszu` -> `NearestAttackableTargetGoal`, `C_16xvdchlc` -> `NearestTargetGoal`, `C_94dijdhgf` -> `NearestAttackablePlayerGoal`.
> 
> Also a few other comments:
> 
>     * Generally, use `pos` not `blockPos`, `state` not `blockState`, `stack` not `itemStack`, `client` not `mcClient`.
> 
>     * Generally, don't put the type of a field/method in its name: `getFishLoot` not `getFishLootList`, `target` not `targetEntity`, `mob` not `mobEntity`, etc. There are exceptions but most of the time these type descriptors are redundant and could (or should) be replaced by a descriptor of what the field/method is used for (e.g. `followTarget` or `attackTarget` rather than `targetEntity`).

Alright, I'll go and edit them, and thanks for the tips

2022-12-02 17:23 UTC, MaheEvil commented
And about the names for the goals, Yea those names sounds alright.

Although I am not exactly sure about the two goals being `NearestTargetGoal` and `NearestAttackableTargetGoal`, it would sure be an improvement over the current names of ActiveTargetGoal, but still both in a sense try to find "attack-able" target mobs

2022-12-02 17:26 UTC, SpaceWalkerRS commented
> Although I am not exactly sure about the two goals being `NearestTargetGoal` and `NearestAttackableTargetGoal`, it would sure be an improvement over the current names of ActiveTargetGoal, but still both in a sense try to find "attack-able" target mobs

That's a fair point. I struggle to come up with good names that don't just boil down to adding `ForPathAwareMobs` to one of them, which sounds very clunky.

2022-12-02 17:32 UTC, MaheEvil commented
> > Although I am not exactly sure about the two goals being `NearestTargetGoal` and `NearestAttackableTargetGoal`, it would sure be an improvement over the current names of ActiveTargetGoal, but still both in a sense try to find "attack-able" target mobs
> 
> That's a fair point. I struggle to come up with good names that don't just boil down to adding `ForPathAwareMobs` to one of them, which sounds very clunky.

Yes, We can either use a really clunky and long name, or have a decent enough name with java-docs to clarify.
Since I am struggling to even come with a name that is clunky but clear, will probably have to go with the latter option unless someone else has a better suggestion

2022-12-09 03:15 UTC, SpaceWalkerRS commented
My vote goes to changing them up. I'm not too fond of the current name.

2022-12-09 03:23 UTC, SpaceWalkerRS requested changes

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/1.3.tiny
> +		p	8		itemStack
`stack`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/1.4.5#12w49a.tinydiff
> +		p	8			itemStack
`stack`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/1.7.4#14w02a.tinydiff
> +		p	5			blockPos
`pos`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w05b#14w06a.tinydiff
> +	f	Lnet/minecraft/C_66oqmtrvn;	f_82tfscilk		slimeEntity
`sime`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w05b#14w06a.tinydiff
> +c	net/minecraft/C_66oqmtrvn$C_24nqbpjus		LeapTowardsTargetEntityGoal
`LeapTowardsTargetGoal` is more consistent with the other target goals

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w05b#14w06a.tinydiff
> +	f	Z	f_09gnkzzhn		hasTargetEntity
`hasTarget`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w05b#14w06a.tinydiff
> +	f	Lnet/minecraft/C_97zulxhng;	f_54kjtdzlp		targetEntity
`target`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w10c#14w11a.tinydiff
> +	f	Lcom/google/common/base/Predicate;	f_23hectams		targetEntityFilter
`targetFilter`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w27b#14w28a.tinydiff
> +	f	Lnet/minecraft/C_17agfiprw;	f_63iwqbtzw		blockState
`state`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w27b#14w28a.tinydiff
> +		p	8			blockState
`state`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w27b#14w28a.tinydiff
> +	f	Lcom/google/common/base/Predicate;	f_59uavvhbh		targetEntityFilter
`targetFilter`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w27b#14w28a.tinydiff
> +	f	Lnet/minecraft/C_97zulxhng;	f_23jkexjie		targetEntity
`target`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/14w27b#14w28a.tinydiff
> +		p	1			targetEntity
`target`

2022-12-09 03:23 UTC, SpaceWalkerRS commented on mappings/15w38a#15w38b.tinydiff
> +		p	5		blockPos
`pos`

2022-12-09 03:41 UTC, SpaceWalkerRS approved these changes

2022-12-09 03:46 UTC, SpaceWalkerRS commented
conflicts have been resolved, once the build action completes I'll merge

2022-12-09 03:57 UTC, merged